### ISSUE TITLE
Find out how to get a custom domain in AWS Gateway API (and then get one)

### ISSUE THREAD

**Issue by matthew-andrews** [Financial-Times/next-url-management-api#114]
I _think_ we need someone to set up some certificates for us… (in `eu-west-1`).  Greg C, Anurag K, Alan T will all know…

Maybe: `urlmgmtapi.in.ft.com` and `test-urlmgmgtapi.in.ft.com`

Or perhaps we could have one — `urlmgmtapi.in.ft.com` and then map `/production` to prod and `/test` to test.

Whatever other people do probably should just copy them…

Mr Leanse, mind taking this on?

**Comment by TheoLeanse** [comment]
👌 sounds good!

**Comment by matthew-andrews** [comment]
💥
